import './globals.css'
import 'tailwindcss/tailwind.css'
import UserInfoProvider from './contexts/usercontext.js'
import Navbar from './navbar/page'
export const metadata = {
  title: 'Next Auth App',
  description: 'Generated by create next app',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className='w-full bg-gradient-to-r from-red-400 to-orange-200'>

        <UserInfoProvider>
          <Navbar/>
          {children}
        </UserInfoProvider>
      </body>
    </html>
  )
}
